# Generated by Django 3.2.18 on 2023-04-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
