# Generated by Django 4.2 on 2023-05-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0002_passenger_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='email',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='lastname',
        ),
    ]
