# Generated by Django 4.2 on 2023-05-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0003_remove_passenger_email_remove_passenger_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='id_user_P',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
