# Generated by Django 4.2 on 2023-05-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0005_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
