# Generated by Django 4.2 on 2023-05-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0007_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='workerreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=50)),
                ('Discrbition', models.TextField()),
            ],
        ),
    ]
