# Generated by Django 4.2 on 2023-05-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0008_workerreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
