# Generated by Django 4.2 on 2023-05-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0006_workerreports'),
        ('Boards', '0009_worker_email'),
    ]

    operations = [
    ]
