# Generated by Django 4.2 on 2023-05-31 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0010_flight_order'),
        ('Boards', '0010_merge_0006_workerreports_0009_worker_email'),
    ]

    operations = [
    ]
